version: "3"
services:
  postgres:
    image: postgres:15.1
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
 
  pgadmin:
    image: dpage/pgadmin4:6.18
    ports:
      - "8080:80"
    env_file:
      - .env
 
